rvm:
  - 1.9.2
  - 1.9.3
before_script:
  - 'cp spec/dummy/config/database.travisci.yml spec/dummy/config/database.yml'
  - 'sh -e /etc/init.d/xvfb start'
env:
  - DISPLAY=':99.0' CUCUMBER_OPTS='-f progress'
script: bundle exec rake --trace
notifications:
  email:
    - gvarela@gmail.com

